services:
  - type: web
    name: student-info-app
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: student-db
          property: connectionString

databases:
  - name: student-db
    databaseName: studentdb
    user: studentuser